name: Deploy and Update Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code from GitHub Repository
        uses: actions/checkout@v3

    
      - name: SSH into Server and Pull Latest Changes
        run: |
          ssh -i ~/.ssh/id_rsa -p " "${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}" "cd ISTE-501 && git pull origin main"
          
      - name: Clean up SSH key
        run: rm -f ~/.ssh/id_rsa
