name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH and Git Pull
        uses: actions/github-script@v6
        with:
          script: |
            const SSH_PRIVATE_KEY = '${{ secrets.SSH_PRIVATE_KEY }}';
            const SERVER_IP = '${{ secrets.SERVER_IP }}';
            const SERVER_USERNAME = '${{ secrets.SERVER_USERNAME }}';
            const SERVER_PORT = '${{ secrets.SERVER_PORT || 22 }}'; // Default to 22 if not set

            // Create a temporary SSH key file
            const fs = require('fs');
            fs.writeFileSync('id_rsa', SSH_PRIVATE_KEY + '\n');
            fs.chmodSync('id_rsa', '600'); // Set correct permissions

            // SSH and Git Pull
            try {
              await exec.exec('ssh', [
                '-p', SERVER_PORT,
                '-i', 'id_rsa',
                `${SERVER_USERNAME}@${SERVER_IP}`,
                `cd /path/to/your/repo && git pull origin main`, // Replace with your path and branch
              ]);
            } finally {
              fs.unlinkSync('id_rsa'); // Clean up the temporary key file
            }
         
