name: SSH into Server and Run Command

on:
  push:
    branches:
      - main  # Adjust the branch name as needed
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  ssh:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up SSH key
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.SERVER_HOST }}  # Your server's IP or domain
          username: ${{ secrets.SERVER_USER }}  # Your server's SSH username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key secret
          port: 22  # Default SSH port
          script: |
            # Command to run on the server
            ls
            # You can replace the line above with any command you'd like to run
